apiVersion: apps/v1
kind: Deployment
metadata:
  name: newswebapp-deployment
  labels:
    app: newswebapp
spec:
  replicas: 3
  template:
    metadata:
      name: newswebapp-pod
      labels:
        app: newswebapp
    spec:
      containers:
        - name: newswebapp-container
          image: vaibhavvadgama/newswebapp
  selector:
    matchLabels:
      app: newswebapp
