apiVersion: v1
kind: Service
metadata:
  name: newswebapp-service-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30001
  selector:
    app: newswebapp