name: VV News Webapp Docker Build/Publish workflow

on:
  push:
    branches:
      - main
      - develop

jobs:
  docker-build-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: PRE_BUILD_IMAGE_LIST
      run: docker images
    - name: LOGIN_TO_DOCKER_HUB
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME_VV }}
        password: ${{ secrets.DOCKER_PASSWORD_VV }}
    - name: BUILD_AND_PUBLISH_DOCKER_IMAGE
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: vaibhavvadgama/newswebapp
    - name: LIST_IMAGES_POST_BUILD
      run: docker images
